---
kb_fingers:
  tlde: lf5
  ae01: lf5
  ae02: lf4
  ae03: lf3
  ae04: lf2
  ae05: lf2
  ae06: rf2
  ae07: rf2
  ae08: rf3
  ae09: rf4
  ae10: rf5
  ae11: rf5
  ae12: rf5
  bksp: rf5
  tab: lf5
  ad01: lf5
  ad02: lf4
  ad03: lf3
  ad04: lf2
  ad05: lf2
  ad06: rf2
  ad07: rf2
  ad08: rf3
  ad09: rf4
  ad10: rf5
  ad11: rf5
  ad12: rf5
  caps: lf5
  ac01: lf5
  ac02: lf4
  ac03: lf3
  ac04: lf2
  ac05: lf2
  ac06: rf2
  ac07: rf2
  ac08: rf3
  ac09: rf4
  ac10: rf5
  ac11: rf5
  bksl: rf5
  rtrn: rf5
  lfsh: lf5
  ab01: lf5
  ab02: lf4
  ab03: lf3
  ab04: lf2
  ab05: lf2
  ab06: lf2
  ab07: rf2
  ab08: rf3
  ab09: rf4
  ab10: rf5
  rtsh: rf5
  lctl: none
  lwin: none
  lalt: none
  spce: rf1
  ralt: none
  rwin: none
  comp: none
  rctl: none
