---
kb_rows:
  tlde: r0
  ae01: r0
  ae02: r0
  ae03: r0
  ae04: r0
  ae05: r0
  ae06: r0
  ae07: r0
  ae08: r0
  ae09: r0
  ae10: r0
  ae11: r0
  ae12: r0
  bksp: r0
  tab: r1
  ad01: r1
  ad02: r1
  ad03: r1
  ad04: r1
  ad05: r1
  ad06: r1
  ad07: r1
  ad08: r1
  ad09: r1
  ad10: r1
  ad11: r1
  ad12: r1
  caps: r2
  ac01: r2
  ac02: r2
  ac03: r2
  ac04: r2
  ac05: r2
  ac06: r2
  ac07: r2
  ac08: r2
  ac09: r2
  ac10: r2
  ac11: r2
  bksl: r2
  rtrn: r2
  lfsh: r3
  ab01: r3
  ab02: r3
  ab03: r3
  ab04: r3
  ab05: r3
  ab06: r3
  ab07: r3
  ab08: r3
  ab09: r3
  ab10: r3
  rtsh: r3
  lctl: r4
  lwin: r4
  lalt: r4
  spce: r4
  ralt: r4
  rwin: r4
  comp: r4
  rctl: r4
