---
xkb_list:
  "⇤": "BackSpace"
  "➨": "Tab"
  "⇑": "Shift"
  "⏎": "Return"
  "⊔": "Space"
  "⇕": "Caps_Lock"
  " ": space
  "+": plus
  "!": exclam
  "\"": quotedbl
  "#": numbersign
  "$": dollar
  "%": percent
  "&": ampersand
  "'": apostrophe
  "(": parenleft
  ")": parenright
  "*": asterisk
  ",": comma
  "-": minus
  ".": period
  "/": slash
  ":": colon
  ";": semicolon
  "<": less
  "=": equal
  ">": greater
  "?": question
  "@": at
  "[": bracketleft
  "\\": backslash
  "]": bracketright
  "^": asciicircum
  _: underscore
  "`": grave
  "{": braceleft
  "|": bar
  "}": braceright
  "~": asciitilde
  "¡": exclamdown
  "¢": cent
  "£": sterling
  "¤": currency
  "¥": yen
  "¦": brokenbar
  "§": section
  "¨": diaeresis
  "©": copyright
  ª: ordfeminine
  "«": guillemotleft
  "¬": notsign
  "®": registered
  "¯": macron
  "–": endash
  "—": emdash
  "°": degree
  "±": plusminus
  "²": twosuperior
  "³": threesuperior
  "´": acute
  µ: mu
  "¶": paragraph
  "·": periodcentered
  "¸": cedilla
  "¹": onesuperior
  º: masculine
  "»": guillemotright
  "¼": onequarter
  "½": onehalf
  "¾": threequarters
  "¿": questiondown
  "“": leftdoublequotemark
  "”": rightdoublequotemark
  "‘": leftsinglequotemark
  "’": rightsinglequotemark
  "≤": lessthanequal
  "∞":	infinity
  "⋃":	union
  "∇":	nabla
  "⋂":	intersection
  "∫":	integral
  "≠": notequal
  "≥": greaterthanequal
  "≈": approximate


  À: Agrave
  Á: Aacute
  Â: Acircumflex
  Ã: Atilde
  Ä: Adiaeresis
  Å: Aring
  Æ: AE
  Ç: Ccedilla
  È: Egrave
  É: Eacute
  Ê: Ecircumflex
  Ë: Ediaeresis
  Ì: Igrave
  Í: Iacute
  Î: Icircumflex
  Ï: Idiaeresis
  Ð: ETH
  Ñ: Ntilde
  Ò: Ograve
  Ó: Oacute
  Ô: Ocircumflex
  Õ: Otilde
  Ö: Odiaeresis
  "×": multiply
  Ø: Ooblique
  Ù: Ugrave
  Ú: Uacute
  Û: Ucircumflex
  Ü: Udiaeresis
  Ý: Yacute
  Þ: THORN
  ß: ssharp
  à: agrave
  á: aacute
  â: acircumflex
  ã: atilde
  ä: adiaeresis
  å: aring
  æ: ae
  ç: ccedilla
  è: egrave
  é: eacute
  ê: ecircumflex
  ë: ediaeresis
  ì: igrave
  í: iacute
  î: icircumflex
  ï: idiaeresis
  ð: eth
  ñ: ntilde
  ò: ograve
  ó: oacute
  ô: ocircumflex
  õ: otilde
  ö: odiaeresis
  "÷": division
  ø: oslash
  ù: ugrave
  ú: uacute
  û: ucircumflex
  ü: udiaeresis
  ý: yacute
  þ: thorn
  ÿ: ydiaeresis
  Ś: acute
  Ş: Scedilla
  Ź: Zacute
  ś: acute
  ş: scedilla
  ź: zacute
  Ŕ: Racute
  Ĺ: Lacute
  Ć: Cacute
  Ń: Nacute
  ŕ: acute
  ĺ: lacute
  ć: cacute
  ń: acute
  Ŗ: Rcedilla
  Ĩ: Itilde
  Ļ: Lcedilla
  Ģ: Gcedilla
  ŗ: rcedilla
  ĩ: itilde
  ļ: lcedilla
  Ņ: cedilla
  Ķ: Kcedilla
  Ũ: Utilde
  ņ: cedilla
  ķ: kcedilla
  ũ: utilde
  Ÿ: diaeresis
  ю: yrillic_yu
  а: Cyrillic_a
  б: Cyrillic_be
  ц: Cyrillic_tse
  д: Cyrillic_de
  е: Cyrillic_ie
  ф: Cyrillic_ef
  г: Cyrillic_ghe
  х: Cyrillic_ha
  и: Cyrillic_i
  й: Cyrillic_shorti
  к: Cyrillic_ka
  л: Cyrillic_el
  м: Cyrillic_em
  н: Cyrillic_en
  о: Cyrillic_o
  п: Cyrillic_pe
  я: Cyrillic_ya
  р: Cyrillic_er
  с: Cyrillic_es
  т: Cyrillic_te
  у: Cyrillic_u
  ж: Cyrillic_zhe
  в: Cyrillic_ve
  ь: Cyrillic_softsign
  ы: Cyrillic_yeru
  з: Cyrillic_ze
  ш: Cyrillic_sha
  э: Cyrillic_e
  щ: Cyrillic_shcha
  ч: Cyrillic_che
  ъ: Cyrillic_hardsign
  Ю: Cyrillic_YU
  А: Cyrillic_A
  Б: Cyrillic_BE
  Ц: Cyrillic_TSE
  Д: Cyrillic_DE
  Е: Cyrillic_IE
  Ф: Cyrillic_EF
  Г: Cyrillic_GHE
  Х: Cyrillic_HA
  И: Cyrillic_I
  Й: Cyrillic_SHORTI
  К: Cyrillic_KA
  Л: Cyrillic_EL
  М: Cyrillic_EM
  Н: Cyrillic_EN
  О: Cyrillic_O
  П: Cyrillic_PE
  Я: Cyrillic_YA
  Р: Cyrillic_ER
  С: Cyrillic_ES
  Т: Cyrillic_TE
  У: Cyrillic_U
  Ж: Cyrillic_ZHE
  В: Cyrillic_VE
  Ь: Cyrillic_SOFTSIGN
  Ы: Cyrillic_YERU
  З: Cyrillic_ZE
  Ш: Cyrillic_SHA
  Э: Cyrillic_E
  Щ: Cyrillic_SHCHA
  Ч: Cyrillic_CHE
  Ъ: Cyrillic_HARDSIGN
  €: EuroSign
  Α: Greek_ALPHA
  Β: Greek_BETA
  Γ: Greek_GAMMA
  Δ: Greek_DELTA
  Ε: Greek_EPSILON
  Ζ: Greek_ZETA
  Η: Greek_ETA
  Θ: Greek_THETA
  Ι: Greek_IOTA
  Κ: Greek_KAPPA
  Λ: Greek_LAMBDA
  Μ: Greek_MU
  Ν: Greek_NU
  Ξ: Greek_XI
  Ο: Greek_OMICRON
  Π: Greek_PI
  Ρ: Greek_RHO
  Σ: Greek_SIGMA
  Τ: Greek_TAU
  Υ: Greek_UPSILON
  Φ: Greek_PHI
  Χ: Greek_CHI
  Ψ: Greek_PSI
  Ω: Greek_OMEGA
  α: Greek_alpha
  β: Greek_beta
  γ: Greek_gamma
  δ: Greek_delta
  ε: Greek_epsilon
  ζ: Greek_zeta
  η: Greek_eta
  θ: Greek_theta
  ι: Greek_iota
  κ: Greek_kappa
  λ: Greek_lambda
  µ: Greek_mu
  ν: Greek_nu
  ξ: Greek_xi
  ο: Greek_omicron
  π: Greek_pi
  ρ: Greek_rho
  σ: Greek_sigma
  #    :Greek_finalsmallsigma
  τ: Greek_tau
  υ: Greek_upsilon
  φ: Greek_phi
  χ: Greek_chi
  ψ: Greek_psi
  ω: Greek_omega
